name: Merge IPTV Playlists from URLs

on:
  workflow_dispatch:
  schedule:
    - cron: '*/17 * * * *' # jalan tiap 1 jam sekali (UTC)

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and merge playlists
        run: |
          echo "#EXTM3U" > merged.m3u
          for url in \
            "https://gitlab.com/ridjals739/ppv-playlist/-/raw/main/myplaylist.m3u" \
            "https://raw.githubusercontent.com/srhady/axsports/refs/heads/main/playlist.m3u"
          do
            echo "Merging $url"
            curl -sfL "$url" | tail -n +2 >> merged.m3u || echo "# Failed to load $url" >> merged.m3u
          done

          echo "# Merge updated on $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> merged.m3u

      - name: Commit and force push merged file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add merged.m3u
          git commit -m "Auto merge playlists from URL [$(date -u +"%Y-%m-%dT%H:%M:%SZ")]" || echo "No changes to commit"

          git fetch origin main
          git reset --hard origin/main
          git add merged.m3u
          git commit -m "Force update merged playlist [$(date -u +"%Y-%m-%dT%H:%M:%SZ")]" || true
          git push origin HEAD:main --force
